### ISSUE TITLE
Zooming out on large images

### ISSUE THREAD

**Issue by hidden-r4d** [Blobfolio/refract#2]
I can't seem to find an option to zoom out on large images, making this unusable for very large images, and a chore to use for large ones.

**Comment by joshstoik1** [comment]
Hi @hidden-r4d,

Zooming/rescaling is not supported as that would mask the types of compression artifacts the program is designed to help you hunt for.

But the image area is _scrollable_, so you should still be able to visually inspect the entire image, even if it is larger than your window/monitor. That might not be obvious as some GNOME themes hide scrollbars unless the mouse hovers over the region, but they should be there! (If not, your system's older GTK libraries might not be entirely compatible.)
