### ISSUE TITLE
Failed to verify the checksum of `jpegxl-sys v0.8.1+libjxl-0.8.1` error when run clippy

### ISSUE THREAD

**Issue by luzfcb** [Blobfolio/refract#5]
Hello, I'm trying to compile `refract` via docker and I'm running `just` inside docker, and when running `just clippy` I got the error

```
$ just clippy
 Updating crates.io index
 ... # A lot of logs

#0 72.96 error: failed to verify the checksum of `jpegxl-sys v0.8.1+libjxl-0.8.1`
#0 72.96 error: Recipe `clippy` failed on line 91 with exit code 101
```
As commented in https://github.com/inflation/jpegxl-rs/issues/20#issuecomment-1501380021 , the solution was to upgrade to the `jpegxl-rs` version to `0.8.2-alpha`

**Comment by joshstoik1** [comment]
Thanks for digging into this, @luzfcb! I just merged your PR (along with a few pedantic lints), so hopefully that'll fix the issue for you.

You might prefer `cargo` to `just` for tasks like linting and building, FYI. The `justfile` recipes don't do anything fancy, but _do_ override `--target=x86_64-unknown-linux-gnu` and `--target-dir=/tmp/refract-cargo`, which might not be desirable depending on your needs. :wink: 

(If you are building for a different platform, or not using a Debian base image, please let me know how it goes and/or anything special dependency-wise you had to do to get it working. I'll update the README accordingly.)
